// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20230201220951_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsComplete = false,
                            Name = "TEST",
                            Secret = "SECRET"
                        },
                        new
                        {
                            Id = 2,
                            IsComplete = false,
                            Name = "TEST-2",
                            Secret = "SECRET"
                        },
                        new
                        {
                            Id = 3,
                            IsComplete = true,
                            Name = "TEST-3",
                            Secret = "SECRET"
                        },
                        new
                        {
                            Id = 4,
                            IsComplete = false,
                            Name = "TEST-4",
                            Secret = "SECRET"
                        },
                        new
                        {
                            Id = 5,
                            IsComplete = true,
                            Name = "TEST-5",
                            Secret = "SECRET"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
