// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApiDTO.DAL.Contexts;

namespace TodoApiDTO.DAL.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20221111142347_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoApiDTO.DAL.Entities.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 11, 11, 18, 23, 47, 326, DateTimeKind.Local).AddTicks(3345),
                            IsComplete = true,
                            ModifiedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3012),
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3511),
                            IsComplete = false,
                            ModifiedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3525),
                            Name = "Name2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3536),
                            IsComplete = false,
                            ModifiedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3537),
                            Name = "Name3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3538),
                            IsComplete = true,
                            ModifiedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3539),
                            Name = "Name4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3542),
                            IsComplete = true,
                            ModifiedDate = new DateTime(2022, 11, 11, 18, 23, 47, 327, DateTimeKind.Local).AddTicks(3543),
                            Name = "Name5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
